src/posts/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name="list"),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<id>\d+)/$', post_detail, name='detail'),
    url(r'^(?P<id>\d+)/edit/$', post_update, name="update"),
    url(r'^(?P<id>\d+)/delete/$', post_delete, name='delete'),
]

src/trydjango19/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/models.py
from django.db import models


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=250)
    image = models.ImageField(null=True,
                              upload_to=upload_location,
                              blank=True,
                              width_field="image_width",
                              height_field="image_height")
    image_width = models.IntegerField(default=0)
    image_height = models.IntegerField(default=0)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/posts/%s/" % (self.id)

    def get_edit_url(self):
        return "%s/edit/" % (self.id)

    class Meta:
        ordering = ["-timestamp", "-updated"]

src/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image"
        ]

src/posts/views.py
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post
from .forms import PostForm


# Create your views here.

def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully created!")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": "Create Post",
        "form": form
    }
    return render(request, "post_form.html", context)


def post_detail(request, id=None):
    instance = get_object_or_404(Post, id=id)

    context = {
        "title": instance.title,
        'instance': instance
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    posts_list = Post.objects.all()

    query =  request.GET['query'] if 'query' in request.GET else None

    print(query)
    if query is not None:
        posts_list = Post.objects.all().filter(title__icontains=query) |\
            Post.objects.all().filter(content__icontains=query)

    paginator = Paginator(posts_list, 5) # Show 25 contacts per page
    page_request_var = 'page'

    page = request.GET.get(page_request_var)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)


    context = {
        "title": "List",
        "posts_list": posts,
        "page_request_var": page_request_var,
        "query": query
    }

    return render(request, "post_list.html", context)


def post_update(request, id=None):
    instance = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully updated!")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }

    return render(request, "post_form.html", context)


def post_delete(request, id=None):
    instance = get_object_or_404(Post, id=id)
    instance.delete()
    messages.success(request, "Successfully deleted!")

    return redirect("posts:list")

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %} Try django {% endblock head_title %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-material-design/bootstrap-material-design.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-material-design/ripples.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>
<body>
<header>
    <div class="bs-component">
        <div class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-responsive-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'posts:list' %}">Posts</a>
                </div>
                <div class="navbar-collapse collapse navbar-responsive-collapse">
                    <ul class="nav navbar-nav">
                        <li class="{% ifequal request.path '/posts/create/'%} active {% endifequal%}"><a href="{% url 'posts:create' %}">Create</a></li>
                        <li class="dropdown">
                            <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle"
                               data-toggle="dropdown">Dropdown
                                <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="javascript:void(0)">Action</a></li>
                                <li><a href="javascript:void(0)">Another action</a></li>
                                <li><a href="javascript:void(0)">Something else here</a></li>
                                <li class="divider"></li>
                                <li class="dropdown-header">Dropdown header</li>
                                <li><a href="javascript:void(0)">Separated link</a></li>
                                <li><a href="javascript:void(0)">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left" action="{% url 'posts:list' %}" method="GET" accept-charset="utf-8">
                        <div class="form-group is-empty">
                            <input type="text" name="query" class="form-control col-md-8" placeholder="Search">
                            <span class="material-input"></span>
                        </div>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="javascript:void(0)">Link</a></li>
                        <li class="dropdown">
                            <a href="bootstrap-elements.html" data-target="#" class="dropdown-toggle"
                               data-toggle="dropdown">Dropdown
                                <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="javascript:void(0)">Action</a></li>
                                <li><a href="javascript:void(0)">Another action</a></li>
                                <li><a href="javascript:void(0)">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="javascript:void(0)">Separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
{% if messages %}
<div class="messages">
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</div>
{% endif %}

<div class="container">
{% block content %}

{% endblock content %}
</div>

<script src="{% static 'js/jquery/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap-material-design/ripples.js' %}"></script>
<script src="{% static 'js/bootstrap-material-design/material.js' %}"></script>
<script src="{% static 'js/base.js' %}"></script>
</body>
</html>

src/templates/post_detail.html
{% extends "base.html" %}

{% block head_title %} {{ instance.title }} | {{ block.super }} {% endblock head_title %}


{% block content %}

<div class="col-sm-6 col-sm-offset-3">
    <div class="row">
        <div class="">
            <img src="{% if instance.image %}{{instance.image.url}}{% else %}http://placehold.it/600x400{% endif %}" alt="" class="img-responsive">
        </div>
        <h1>{{ instance.title }} <small>{{ instance.timestamp }}</small></h1>

        <p>
            {{ instance.content | linebreaks }}
        </p>

    </div>

    <div class="row">
        <h2>
            <a href="edit/">Edit</a>
        </h2>
        <h2>
            <a href="delete/">Delete</a>
        </h2>
    </div>
</div>
{% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}

{% block head_title %} Create or edit post | {{ block.super }} {% endblock head_title %}

{% block content %}

<!--<form method="POST" action="">{% csrf_token %}
{{ form.as_p }}

<input type="submit" value="Create post">
</form>-->

<div class="well bs-component">
<form class="form-horizontal" method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
  <fieldset>
    <legend>Create or edit post</legend>
    <div class="form-group">
      <label for="title" class="col-md-2 control-label">Title</label>

      <div class="col-md-10">
        <input type="text" class="form-control" name="title" id="title" value="{{ instance.title }}" placeholder="Title">
      </div>
    </div>
      
    <div class="form-group">
      <label for="content" class="col-md-2 control-label">Content</label>

      <div class="col-md-10">
        <textarea class="form-control" rows="3" name="content" id="content">{{ instance.content }}</textarea>
      </div>
    </div>

    <div class="form-group is-empty is-fileinput">
      <label for="image" class="col-md-2 control-label">Image</label>

      <div class="col-md-10">
        <input type="text" readonly="" class="form-control" placeholder="Browse...">
        <input type="file" name="image" id="image" multiple="">
      </div>
      <span class="material-input"></span>
    </div>
    
    <div class="form-group">
      <div class="col-md-10 col-md-offset-2">
        <button type="button" class="btn btn-default">Cancel</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form>
</div>

{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}

{% block head_title %} Posts list | {{ block.super }} {% endblock head_title %}

{% block content %}

    {% if query %}
        <h1><small>Search:</small> {{ query }}</h1>
    {% endif %}
    <div class="row">
        {% for obj in posts_list %}
            <div class="col-md-4">
                <div class="bs-component">
                    <div class="well infobox">
                        <h1><a href='{{ obj.get_absolute_url }}'>{{ obj.title }}</a></h1>
                        <p>
                            {{ obj.content | linebreaks }}
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
        <div class="row">
        <div class="pagination">
            <span class="step-links">
                {% if posts_list.has_previous %}
                    <a href="?{{ page_request_var }}={{ posts_list.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ posts_list.number }} of {{ posts_list.paginator.num_pages }}.
                </span>

                {% if posts_list.has_next %}
                    <a href="?{{ page_request_var }}={{ posts_list.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock content %}